### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by ajolo2ky** [dazzletheweb/mautic-sendinblue#1]
Hi there ! thanks for developing this plugin. I'm trying to use it on Mautic 2.15.2 (built with a Bitnami image) and I get this error when trying to send a test email. I created the API key and put it in the settings page (test connection works ok, test email fails with error 500). I've also set the webhooks on SendinBlue's page.

Thanks,

`[2019-12-14 10:38:33] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Configuration" from namespace "SendinBlue\Client". Did you forget a "use" statement for e.g. "OpenCloud\Database\Resource\Configuration", "Oneup\UploaderBundle\DependencyInjection\Configuration", "Noxlogic\RateLimitBundle\DependencyInjection\Configuration", "LightSaml\SymfonyBridgeBundle\DependencyInjection\Configuration", "LightSaml\SpBundle\DependencyInjection\Configuration", "JMS\SerializerBundle\DependencyInjection\Configuration", "FOS\RestBundle\DependencyInjection\Configuration", "Doctrine\ORM\Configuration", "Doctrine\DBAL\Configuration", "Debril\RssAtomBundle\DependencyInjection\Configuration", "Symfony\Bundle\WebProfilerBundle\DependencyInjection\Configuration", "Symfony\Bundle\TwigBundle\DependencyInjection\Configuration", "Symfony\Bundle\SwiftmailerBundle\DependencyInjection\Configuration", "Symfony\Bundle\MonologBundle\DependencyInjection\Configuration", "Symfony\Bundle\FrameworkBundle\Tests\Functional\Bundle\TestBundle\DependencyInjection\Configuration", "Symfony\Bundle\FrameworkBundle\DependencyInjection\Configuration", "Sonata\Exporter\Bridge\Symfony\DependencyInjection\Configuration", "Sensio\Bundle\FrameworkExtraBundle\DependencyInjection\Configuration", "OldSound\RabbitMqBundle\DependencyInjection\Configuration", "Liip\FunctionalTestBundle\DependencyInjection\Configuration", "Leezy\PheanstalkBundle\DependencyInjection\Configuration", "Knp\Bundle\MenuBundle\DependencyInjection\Configuration", "FOS\OAuthServerBundle\DependencyInjection\Configuration", "Exporter\Bridge\Symfony\DependencyInjection\Configuration", "Doctrine\DBAL\Migrations\Configuration\Configuration", "Doctrine\Bundle\MigrationsBundle\DependencyInjection\Configuration", "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\Configuration", "Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration", "Codeception\Configuration", "Bazinga\OAuthServerBundle\DependencyInjection\Configuration", "Aws\EndpointDiscovery\Configuration", "Aws\Sts\RegionalEndpoints\Configuration" or "Aws\ClientSideMonitoring\Configuration"?" at /opt/bitnami/apps/mautic/htdocs/plugins/MauticSendinblueBundle/Swiftmailer/Transport/SendinblueApiTransport.php line 134 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Configuration\" from namespace \"SendinBlue\\Client\".\nDid you forget a \"use\" statement for e.g. \"OpenCloud\\Database\\Resource\\Configuration\", \"Oneup\\UploaderBundle\\DependencyInjection\\Configuration\", \"Noxlogic\\RateLimitBundle\\DependencyInjection\\Configuration\", \"LightSaml\\SymfonyBridgeBundle\\DependencyInjection\\Configuration\", \"LightSaml\\SpBundle\\DependencyInjection\\Configuration\", \"JMS\\SerializerBundle\\DependencyInjection\\Configuration\", \"FOS\\RestBundle\\DependencyInjection\\Configuration\", \"Doctrine\\ORM\\Configuration\", \"Doctrine\\DBAL\\Configuration\", \"Debril\\RssAtomBundle\\DependencyInjection\\Configuration\", \"Symfony\\Bundle\\WebProfilerBundle\\DependencyInjection\\Configuration\", \"Symfony\\Bundle\\TwigBundle\\DependencyInjection\\Configuration\", \"Symfony\\Bundle\\SwiftmailerBundle\\DependencyInjection\\Configuration\", \"Symfony\\Bundle\\MonologBundle\\DependencyInjection\\Configuration\", \"Symfony\\Bundle\\FrameworkBundle\\Tests\\Functional\\Bundle\\TestBundle\\DependencyInjection\\Configuration\", \"Symfony\\Bundle\\FrameworkBundle\\DependencyInjection\\Configuration\", \"Sonata\\Exporter\\Bridge\\Symfony\\DependencyInjection\\Configuration\", \"Sensio\\Bundle\\FrameworkExtraBundle\\DependencyInjection\\Configuration\", \"OldSound\\RabbitMqBundle\\DependencyInjection\\Configuration\", \"Liip\\FunctionalTestBundle\\DependencyInjection\\Configuration\", \"Leezy\\PheanstalkBundle\\DependencyInjection\\Configuration\", \"Knp\\Bundle\\MenuBundle\\DependencyInjection\\Configuration\", \"FOS\\OAuthServerBundle\\DependencyInjection\\Configuration\", \"Exporter\\Bridge\\Symfony\\DependencyInjection\\Configuration\", \"Doctrine\\DBAL\\Migrations\\Configuration\\Configuration\", \"Doctrine\\Bundle\\MigrationsBundle\\DependencyInjection\\Configuration\", \"Doctrine\\Bundle\\DoctrineCacheBundle\\DependencyInjection\\Configuration\", \"Doctrine\\Bundle\\DoctrineBundle\\DependencyInjection\\Configuration\", \"Codeception\\Configuration\", \"Bazinga\\OAuthServerBundle\\DependencyInjection\\Configuration\", \"Aws\\EndpointDiscovery\\Configuration\", \"Aws\\Sts\\RegionalEndpoints\\Configuration\" or \"Aws\\ClientSideMonitoring\\Configuration\"? at /opt/bitnami/apps/mautic/htdocs/plugins/MauticSendinblueBundle/Swiftmailer/Transport/SendinblueApiTransport.php:134)"} []`

**Comment by solariel** [comment]
Hi!

Please describe your installation steps. Did you use composer? Is there a 'sendinblue/APIv3-php-library' in your vendor directory?

SendinBlue SDK hasn't changed since this was tested and the error message is telling that there is no 'Configuration' class found in SDK. It's strange.

UPD: Sorry for the 'Install from .zip' option. It doesn't work and has been removed. The only way to correctly install this plugin is via composer.

**Comment by ajolo2ky** [comment]
Hi, I've used Bitnami's Mautic AMI found in Lightsail. I copied the repo's
code into the plug-ins directory and enabled it from Mautic's
configuration.

**Comment by solariel** [comment]
Understood. As I've written in the previous comment, for now the only way to correctly install this plugin is to do it with composer. Please see the updated README.

Closing for now. We'll think about how to facilitate installation without composer usage.
