### ISSUE TITLE
Emails being added in To: field ?

### ISSUE THREAD

**Issue by ajolo2ky** [dazzletheweb/mautic-sendinblue#2]
Hi, I'm using the plugin and I see campaigns get send with users being added in the To field, making the contact list visible for everybody.

**Comment by ojacquet** [comment]
Can you please confirm that the behavior via this plugin is different than using PHP mail? It is unlikely that it is the plugin that chooses to add emails to the TO field instead of another field.

**Comment by ajolo2ky** [comment]
Confirmed, I'm only using the plugin. Simple campaign format, using one list as source and sending one email. Receipients got added in the To: field, so only one email went out, with multiple destinataries.

![image](https://user-images.githubusercontent.com/6595356/71826673-32d3ad80-307d-11ea-9fdc-656e614aac59.png)

<img width="771" alt="Screenshot 2020-01-06 12 06 23" src="https://user-images.githubusercontent.com/6595356/71826605-0ddf3a80-307d-11ea-994c-84f4fdfdc491.png">

**Comment by rowen92** [comment]
It's fixed in a new release. Please update the package.

**Comment by ojacquet** [comment]
@ajolo2ky Can you confirm that this is fixed?
